export const RealtimeEvents = Object.freeze({
  CALL_STARTED: "call.started",
  CALL_ENDED: "call.ended",
  CALL_FAILED: "call.failed",
  SESSION_CREATED: "session.created",
  SESSION_UPDATED: "session.updated",
  SESSION_CLOSED: "session.closed",
  AUDIO_INCOMING: "audio.incoming",
  AUDIO_BUFFER_COMMITTED: "audio.buffer.committed",
  AUDIO_OUTGOING: "audio.outgoing",
  USER_SPEECH_START: "user.speech.start",
  USER_SPEECH_END: "user.speech.end",
  USER_TRANSCRIPT_FINAL: "user.transcript.final",
  USER_TRANSCRIPT_FAILED: "user.transcript.failed",
  ASSISTANT_SPEECH_START: "assistant.speech.start",
  ASSISTANT_SPEECH_END: "assistant.speech.end",
  INTERRUPT_DETECTED: "interrupt.detected",
  RESPONSE_TEXT_DELTA: "response.text.delta",
  RESPONSE_AUDIO_DELTA: "response.audio.delta",
  RESPONSE_DONE: "response.done",
  LOCAL_RESPONSE_USED: "local.response.used",
  GATE_DECISION: "gate.decision",
  ERROR: "error",
  METRIC: "metric",
});
