[build]
builder = "NIXPACKS"
buildCommand = "npm install"
buildEnvironment = "V3"
 
[deploy]
runtime = "V2"
numReplicas = 1
startCommand = "npm start"
healthcheckPath = "/api/health"
sleepApplication = true
useLegacyStacker = false
ipv6EgressEnabled = false
restartPolicyType = "ON_FAILURE"
healthcheckTimeout = 120
restartPolicyMaxRetries = 10
 
[deploy.multiRegionConfig.sfo]
numReplicas = 1
