export const CALL_EVENTS = Object.freeze({
  CALL_STARTED: "CALL_STARTED",
  USER_SPEECH_STARTED: "USER_SPEECH_STARTED",
  USER_SPEECH_ENDED: "USER_SPEECH_ENDED",
  AI_RESPONSE_STARTED: "AI_RESPONSE_STARTED",
  AI_RESPONSE_INTERRUPTED: "AI_RESPONSE_INTERRUPTED",
  AI_RESPONSE_COMPLETED: "AI_RESPONSE_COMPLETED",
  STATE_CHANGED: "STATE_CHANGED",
  HANDOFF_TRIGGERED: "HANDOFF_TRIGGERED",
  CALL_TERMINATED: "CALL_TERMINATED",
  LATENCY_WARNING: "LATENCY_WARNING",
  FALLBACK_TRIGGERED: "FALLBACK_TRIGGERED",
});

export const ConversationStates = Object.freeze({
  INIT: "INIT",
  GREETING: "GREETING",
  INTENT_CAPTURE: "INTENT_CAPTURE",
  LANGUAGE_DETECTION: "LANGUAGE_DETECTION",
  QUALIFICATION: "QUALIFICATION",
  INFORMATION_DELIVERY: "INFORMATION_DELIVERY",
  BOOKING: "BOOKING",
  TRANSFER: "TRANSFER",
  CALLBACK: "CALLBACK",
  CONFIRMATION: "CONFIRMATION",
  CLOSING: "CLOSING",
  TERMINATED: "TERMINATED",
});
